//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BannersPublicitarios
    {
        [Display(Name = "Código")]
        public long IDBanner { get; set; }

        [Display(Name = "Título da Campanha")]
        [Required(ErrorMessage = "* Obrigatório informar o título da campanha")]
        [StringLength(60, ErrorMessage = "O título deve possuir no máximo 60 caracteres")]
        public string TituloCampanha { get; set; }

        [Display(Name = "Nome do Banner")]
        [Required(ErrorMessage = "* Obrigatório informar o nome do banner")]
        [StringLength(200, ErrorMessage = "O Nome do banner deve possuir no máximo 200 caracteres")]
        public string BannerCampanha { get; set; }

        [Display(Name = "Endereço URL")]
        [StringLength(200, ErrorMessage = "O endereço do link deve possuir no máximo 200 caracteres")]
        public string LinkBanner { get; set; }
    }
}
