//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        [Display(Name = "Código")]
        public long IDUsuario { get; set; }

        [Required(ErrorMessage = "* Obrigatório informar o nome")]
        [StringLength(80, ErrorMessage = "O Nome deve possuir no máximo 80 caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "* Obrigatório informar o login")]
        [StringLength(30, ErrorMessage = "O login deve possuir no máximo 30 caracteres")]
        public string Login { get; set; }

        [Required(ErrorMessage = "* Obrigatório informar a senha")]
        [StringLength(100, ErrorMessage = "A senha deve possuir no máximo 100 caracteres")]
        public string Senha { get; set; }

        [Required(ErrorMessage = "* Obrigatório informar o e-mail")]
        [StringLength(100, ErrorMessage = "O endereço de e-mail deve possuir no máximo 100 caracteres")]
        [Display(Name = "e-mail")]
        [EmailAddress(ErrorMessage = "Endereço de e-mail inválido")]
        public string Email { get; set; }
    }
}
